sudo: required
services:
- docker

before_install:
- cd releng/config
- openssl aes-256-cbc -K $encrypted_fff3b1abfe83_key -iv $encrypted_fff3b1abfe83_iv
  -in ci.tar.enc -out ci.tar -d
- tar -xf ci.tar

script:
- RELEASE=n
- VERSION="$(python setup.py get_version)"
- if [ -n "$TRAVIS_TAG" ]; then RELEASE=y; fi

- docker run --rm -v"$(pwd)":/build/src -u packager -e RELEASE="$RELEASE" -e VERSION="$VERSION" -e TRAVIS=y
  ngld/knossos-builders:ubuntu bash /build/src/releng/ubuntu/auto-build.sh

- docker run --rm -v"$(pwd)":/build/src -u packager -e RELEASE="$RELEASE" -e VERSION="$VERSION" -e TRAVIS=y
  ngld/knossos-builders:arch bash /build/src/releng/arch/auto-build.sh
