version: 0.8.0-dev+appv.{build}
pull_requests:
  do_not_increment_build_number: true

#skip_non_tags: true
clone_depth: 1
clone_folder: C:\knossos
install:
- cmd: >-
    cd C:\knossos
    set "PATH=C:\Python36\Scripts;%PATH%"

    pip install pipenv
    pipenv install

    pipenv run python tools/common/download_archive.py releng/windows/support/support.json

build_script:
- cmd: >-
    cd C:\knossos
    set "PATH=%CD%\releng\windows\support;C:\Python36\Scripts;%PATH%"

    mkdir releng\windows\dist

    pipenv run python tools\common\download_archive.py releng/windows/support/support.json
    pipenv run python tools\common\npm_wrapper.py

    pipenv run python configure.py
    if errorlevel 1 exit /b 1

    ninja installer
artifacts:
- path: releng\windows\dist\Knossos-*.exe
  name: Installer

- path: releng\windows\dist\update-*.exe
  name: Updater

deploy:
- provider: GitHub
  auth_token:
    secure: O3HGtJExInVx0l/ytgKnvWp8r91TJUqGfgEdz75RWXCtnaSONe/CLch8BD2VaLL8

  #on:
  #  appveyor_repo_tag: true