version: 0.8.0-dev+appv.{build}
pull_requests:
  do_not_increment_build_number: true

#skip_non_tags: true
clone_depth: 1
clone_folder: C:\knossos
install:
- cmd: cd C:\knossos && releng\ci\appveyor_install.bat

build_script:
- cmd: cd C:\knossos && releng\ci\appveyor_build.bat

artifacts:
- path: releng\windows\dist\Knossos-*.exe
  name: Installer

- path: releng\windows\dist\update-*.exe
  name: Updater

deploy:
- provider: GitHub
  auth_token:
    secure: O3HGtJExInVx0l/ytgKnvWp8r91TJUqGfgEdz75RWXCtnaSONe/CLch8BD2VaLL8

  #on:
  #  appveyor_repo_tag: true